### ISSUE TITLE
Incorrect Be Year Calculation

### ISSUE THREAD

**Issue by PhanPirang** [ThyrithSor/momentkh#8]
Your Code:
  function getBEYear(moment) {
    if (moment.khMonth() > 5 || moment.khMonth() === 5 && moment.khDay() >= 15) {
      return parseInt(moment.format('YYYY')) + 544;
    } else {
      return parseInt(moment.format('YYYY')) + 543;
    }
  }

What if Khmer Month មគិសិរ start from November in current year?, it will + 543

**Comment by ThyrithSor** [comment]
Do you have any suggestion about this issue?

**Comment by ThyrithSor** [comment]
If you can provide a specific date that result a mistake, it will be easy for me to investigate the problem

**Comment by ThyrithSor** [comment]
Coincidently, today is the example date of the issue. I'll check this soon.

**Comment by ThyrithSor** [comment]
Fixed

**Comment by ThyrithSor** [comment]
Fixed!

Assume that there can't be 2 Khmer New Year event in the same year, I add another condition:
```js
275 >  ....  || moment.diff(newYearMoment) > 0
```
