### ISSUE TITLE
Khmer month

### ISSUE THREAD

**Issue by choubchanthou** [ThyrithSor/momentkh#9]
`['មករា', 'កុម្ភៈ', 'មីនា', 'មេសា', 'ឧសភា', 
'មិថុនា', 'កក្កដា', 'សីហា', 'កញ្ញា', 'តុលា', 'វិច្ឆិកា', 'ធ្នូ']`

**Comment by ThyrithSor** [comment]
Can you explain me what the issue is?

**Comment by choubchanthou** [comment]
I want you to implement months (e.g. January, February, etc) into Khmer as well. Because I do not see in the document.

**Comment by choubchanthou** [comment]
<img width="448" alt="Screen Shot 2020-11-17 at 9 20 24 AM" src="https://user-images.githubusercontent.com/14800691/99338124-33042280-28b6-11eb-9306-a8d8f808f603.png">

It's similar. M => ខែ​ => មករា 

I think

**Comment by ThyrithSor** [comment]
You can try: moment().locale('km').format('MMMM

**Comment by ThyrithSor** [comment]
You can try:
`moment().locale('km').format('MMMM');`
This feature is already in moment.js library so I think I don't have to do it again.

**Comment by ThyrithSor** [comment]
I already added it on b4779a7. Thanks for your suggestion.
